apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
    exporters:
      otlp/metrics:
      otlp/traces:
      debug:
        verbosity:

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [otlp/metrics]
        traces:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [otlp/traces]
